server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: license

  devtools:
    restart:
      enabled: false

license:
  channel:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCN+B4QpQU1QjixzRuKAxKkBi1wZWtoXuzyRKS4Glv8yO4P66mUW9NdX9rQrmLtWwcx4iO18VQMsXS+loVmBODhdaUWzR6uF6mNrAEjFuPhrlVNJ76/8OKin882Mf86SWm6RiR1QhORwCjwhZYehdF9dKmBOqCSKNnsaOStJe9rrQIDAQAB
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAI34HhClBTVCOLHNG4oDEqQGLXBla2he7PJEpLgaW/zI7g/rqZRb011f2tCuYu1bBzHiI7XxVAyxdL6WhWYE4OF1pRbNHq4XqY2sASMW4+GuVU0nvr/w4qKfzzYx/zpJabpGJHVCE5HAKPCFlh6F0X10qYE6oJIo2exo5K0l72utAgMBAAECgYAyh6M7zWBjKmS/c/9fSeSymLhHjvGBvnebay8tj8Q53tJMvFYpRd2fGGTrbYYscP/Ik3KeaXy+39Jrm2tzej0Hun9qDgb6hUfXwPgzczkClrznQcDxQwPVd59x/Z8XzSx0rEFSrDApUkuDBZ11vLDl5ZZ5zbwfd39gi89Vz0zyAQJBAMAJYVjaBRseFU6nqxigk3CslCTUf8DiNC0ZG9fzqA7I3bqsWXN+SgUmxdVD9YEnoDgvolhYIqzKsu6/J5VchUECQQC9QZO5ORYpZ/dQKH6ExBY/8oovcuu0D7QDSMwiD7neCp367hmu5oWJN581J9OFsv0lVkC7zks6T4ltVEdlY+9tAkAyzoiF1HDDYusqOywGQP2hMtejAuGl63L4d4spUFqnRrd7GvwzlTcKM97ldKxwdkZqdxfRncfWxW4fwk07tBXBAkBoPu3i0boOVrEYWyXNdcEXuj45gqCoTxoF0Rx4CpeD4e9BH9PPzjRx78xnWCef9oaQAWGo0SoI1XTKXujwxUpFAkEArzxaT+1Dz/Prh4MYjZXnur60Apzy9S913V8k2I1L7gb6K7CyQgOqzc00c8MDFwzUlaksp7oWGLfB4yM9JNNU9w==
  eni:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCfW+PLSJNE03k5D33CPgUngSpHcXGbIeoRNyzyJmQF2Ocpo/0cw7uXMXDPp46YaDNzRgxonObt5ddQMsNv2DhAZj1o2tfOubUbvTCYEnAKD9Rt0IpZxDMXt4R3Jxw7JAROALWpUrGCfrJiuq8h13ZgIBqohzmccl0j545IBk8wiQIDAQAB